applications:
  - name: example-app
    namespace: default
    project: default
    source:
      repoURL: <https://github.com/YOUR_USERNAME/example-repo.git>
      path: django-chart
      targetRevision: main
      helm:
        valueFiles:
          - values.yaml
    destination:
      server: <https://kubernetes.default.svc>
      namespace: default
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

repositories:
  - name: example-app
    url: <https://github.com/YOUR_USERNAME/example-repo.git>
    username: YOUR_USERNAME
    password: YOUR_PASS

repoConfig:
  insecure: "true"
  enableLfs: "true"
